# Generated by Django 5.1.1 on 2024-11-14 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('husband_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('last_menstrual_period_bs', models.CharField(max_length=10)),
                ('estimated_due_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('checkup_dates_bs', models.JSONField(blank=True, null=True)),
                ('total_iron_intake', models.IntegerField(default=0)),
                ('total_calcium_intake', models.IntegerField(default=0)),
                ('arrival_date', models.CharField(blank=True, max_length=10, null=True)),
                ('ad_arrival_date', models.DateField(blank=True, null=True)),
                ('lmp_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckupVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date_bs', models.CharField(max_length=10)),
                ('visit_week', models.IntegerField()),
                ('iron_intake', models.IntegerField(default=0)),
                ('calcium_intake', models.IntegerField(default=0)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_injection', models.BooleanField(default=False)),
                ('intestinal_parasites_medicine', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='calculator.pregnancycheckup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
