# Generated by Django 5.1.1 on 2024-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkupvisit',
            name='folic_acid',
            field=models.BooleanField(default=False),
        ),
    ]
