# Generated by Django 5.1.1 on 2024-11-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_checkupvisit_folic_acid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkupvisit',
            name='total_calcium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkupvisit',
            name='total_iron',
            field=models.IntegerField(default=0),
        ),
    ]
