# Generated by Django 5.1.1 on 2024-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_pregnancycheckup_calcium_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancycheckup',
            name='lmp_date_ad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancycheckup',
            name='lmp_date_bs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
